<#
.SYNOPSIS
    Configure PowerShell with oh-my-posh, modules, and completions.
#>
param(
    [Parameter(Mandatory)]
    [PSCustomObject]$Config,

    [switch]$DryRun
)

$profilePath = $PROFILE.CurrentUserAllHosts
$profileDir = Split-Path $profilePath -Parent

if (-not (Test-Path $profileDir)) {
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
}

# --- Install oh-my-posh ---

if ($Config.oh_my_posh.enabled) {
    $ompInstalled = Get-Command oh-my-posh -ErrorAction SilentlyContinue
    if (-not $ompInstalled) {
        if ($DryRun) {
            Write-Host "    [DRY RUN] Would install oh-my-posh" -ForegroundColor Yellow
        } else {
            Write-Host "    Installing oh-my-posh..." -ForegroundColor Gray
            winget install JanDeDobbeleer.OhMyPosh -s winget --accept-package-agreements --accept-source-agreements 2>$null
            # Refresh PATH
            $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", "User") + ";" + [System.Environment]::GetEnvironmentVariable("PATH", "Machine")
            Write-Host "    ✓ oh-my-posh installed" -ForegroundColor Green
        }
    } else {
        Write-Host "    ✓ oh-my-posh already installed" -ForegroundColor Green
    }
}

# --- Install PowerShell Modules ---

if ($Config.modules) {
    foreach ($module in $Config.modules) {
        $installed = Get-Module -ListAvailable -Name $module -ErrorAction SilentlyContinue
        if (-not $installed) {
            if ($DryRun) {
                Write-Host "    [DRY RUN] Would install module: $module" -ForegroundColor Yellow
            } else {
                Write-Host "    Installing module: $module..." -ForegroundColor Gray
                Install-Module -Name $module -Scope CurrentUser -Force -AllowClobber -ErrorAction SilentlyContinue
                Write-Host "    ✓ $module installed" -ForegroundColor Green
            }
        } else {
            Write-Host "    ✓ $module already installed" -ForegroundColor Green
        }
    }
}

# --- Generate PowerShell Profile ---

$profileContent = @"
# Windows Nerd Themes - PowerShell Profile
# Generated by windows-nerd-themes installer

"@

# oh-my-posh initialization
if ($Config.oh_my_posh.enabled) {
    $theme = $Config.oh_my_posh.theme
    if ($theme -and $theme -ne "default") {
        $profileContent += @"
# oh-my-posh with theme
oh-my-posh init pwsh --config "`$env:POSH_THEMES_PATH\$theme.omp.json" | Invoke-Expression

"@
    } else {
        $profileContent += @"
# oh-my-posh
oh-my-posh init pwsh | Invoke-Expression

"@
    }
}

# Terminal-Icons
if ($Config.modules -contains "Terminal-Icons") {
    $profileContent += @"
# Terminal Icons
Import-Module Terminal-Icons

"@
}

# PSReadLine configuration
if ($Config.modules -contains "PSReadLine") {
    $profileContent += @"
# PSReadLine - Enhanced command line editing
Set-PSReadLineOption -PredictionSource HistoryAndPlugin
Set-PSReadLineOption -PredictionViewStyle ListView
Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete

"@
}

# Az.Tools.Predictor
if ($Config.modules -contains "Az.Tools.Predictor") {
    $profileContent += @"
# Azure Predictor (IntelliSense for Az CLI)
Import-Module Az.Tools.Predictor

"@
}

# Azure CLI completion
if ($Config.completions.az_cli) {
    $profileContent += @"
# Azure CLI tab completion
Register-ArgumentCompleter -Native -CommandName az -ScriptBlock {
    param(`$commandName, `$wordToComplete, `$cursorPosition)
    `$completion_file = New-TemporaryFile
    `$env:ARGCOMPLETE_USE_TEMPFILES = 1
    `$env:_ARGCOMPLETE_STDOUT_FILENAME = `$completion_file
    `$env:COMP_LINE = `$wordToComplete
    `$env:COMP_POINT = `$cursorPosition
    `$env:_ARGCOMPLETE = 1
    `$env:_ARGCOMPLETE_SUPPRESS_SPACE = 0
    `$env:_ARGCOMPLETE_IFS = "``n"
    `$env:_ARGCOMPLETE_SHELL = 'powershell'
    az 2>&1 | Out-Null
    Get-Content `$completion_file | Sort-Object | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(`$_, `$_, "ParameterValue", `$_)
    }
    Remove-Item `$completion_file, Env:\_ARGCOMPLETE_STDOUT_FILENAME, Env:\ARGCOMPLETE_USE_TEMPFILES, Env:\COMP_LINE, Env:\COMP_POINT, Env:\_ARGCOMPLETE, Env:\_ARGCOMPLETE_SUPPRESS_SPACE, Env:\_ARGCOMPLETE_IFS, Env:\_ARGCOMPLETE_SHELL
}

"@
}

# kubectl completion
if ($Config.completions.kubectl) {
    $profileContent += @"
# kubectl tab completion
if (Get-Command kubectl -ErrorAction SilentlyContinue) {
    kubectl completion powershell | Out-String | Invoke-Expression
}

"@
}

# Aliases
if ($Config.aliases -and $Config.aliases.PSObject.Properties.Count -gt 0) {
    $profileContent += "# Aliases`n"
    foreach ($alias in $Config.aliases.PSObject.Properties) {
        $profileContent += "Set-Alias -Name $($alias.Name) -Value $($alias.Value)`n"
    }
    $profileContent += "`n"
}

# Write profile
if ($DryRun) {
    Write-Host "    [DRY RUN] Would write profile to: $profilePath" -ForegroundColor Yellow
} else {
    # Backup existing profile
    if (Test-Path $profilePath) {
        $backupPath = "$profilePath.backup.$(Get-Date -Format 'yyyyMMdd_HHmmss')"
        Copy-Item $profilePath $backupPath
        Write-Host "    ✓ Backup: $backupPath" -ForegroundColor Green
    }

    $profileContent | Set-Content $profilePath -Encoding UTF8
    Write-Host "    ✓ Profile written to: $profilePath" -ForegroundColor Green
}

Write-Host "  ✓ PowerShell configured" -ForegroundColor Green
